version: 0.2
 
phases:
  install:
    runtime-versions:
      java: corretto11 
    commands:
      - echo Verifying Java version...
      - java -version 
      - javac -version 
      - echo Installing Maven...
      - curl -o apache-maven-3.9.1-bin.zip https://archive.apache.org/dist/maven/maven-3/3.9.1/binaries/apache-maven-3.9.1-bin.zip
      - unzip apache-maven-3.9.1-bin.zip
      - export M2_HOME=$PWD/apache-maven-3.9.1
      - export PATH=$M2_HOME/bin:$PATH
      - mvn -version 
 
  pre_build:
    commands:
      - echo Caching Maven dependencies...
      - mvn dependency:go-offline -B 
 
  build:
    commands:
      - echo Building the application...
      - mvn clean package 
 
  post_build:
    commands:
      - echo Build completed successfully!
 
 
artifacts:
  files:
    - '**/*'   
cache:
  paths:
    - "/root/.m2/**/*" 
